_select_data:
  ratios:
   - square
   - portrait
   - portrait-tall
   - landscape
   - landscape-wide
   - specific-ratio-48

  columns: 
    col-6: half the screen size
    col-12: full width 
    col-4: One Third
    col-3: One Quarter 
    col-6_sm-12: one half desktop / full width on mobile  
    col-4_sm-12: one third desktop / full width on mobile  
    col-3_sm-12: one quarter desktop / full width on mobile  